-- H2 2.4.240;
;             
CREATE USER IF NOT EXISTS "SA" PASSWORD '' ADMIN;             
CREATE CACHED TABLE "PUBLIC"."APP_USERS"(
    "ID" UUID NOT NULL,
    "CREATED_AT" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    "EMAIL" CHARACTER VARYING(150) NOT NULL,
    "FAILED_LOGIN_ATTEMPTS" INTEGER NOT NULL,
    "FULL_NAME" CHARACTER VARYING(150) NOT NULL,
    "LOCKED_UNTIL" TIMESTAMP(6) WITH TIME ZONE,
    "PASSWORD_HASH" CHARACTER VARYING(255),
    "ROLE" ENUM('TENANT_ADMIN', 'TENANT_MANAGER', 'TENANT_USER') NOT NULL,
    "STATUS" ENUM('ACTIVE', 'INACTIVE', 'SUSPENDED') NOT NULL,
    "UPDATED_AT" TIMESTAMP(6) WITH TIME ZONE,
    "TENANT_ID" UUID NOT NULL
);         
ALTER TABLE "PUBLIC"."APP_USERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" PRIMARY KEY("ID");    
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.APP_USERS;               
CREATE CACHED TABLE "PUBLIC"."AUDIT_LOGS"(
    "ID" UUID NOT NULL,
    "ACTION" ENUM('LOGIN_FAILED', 'LOGIN_SUCCESS', 'LOGOUT', 'LOGOUT_ALL', 'PASSWORD_CHANGED', 'PASSWORD_RESET_COMPLETED', 'PASSWORD_RESET_REQUESTED', 'TENANT_DEACTIVATED', 'TENANT_ONBOARDED', 'TENANT_STATUS_UPDATED', 'TENANT_UPDATED', 'TOKEN_REFRESH', 'USER_CREATED', 'USER_DEACTIVATED', 'USER_LOGIN_UNLOCKED', 'USER_ROLE_UPDATED', 'USER_STATUS_UPDATED', 'USER_UPDATED') NOT NULL,
    "ACTOR_TYPE" ENUM('SYSTEM', 'SYSTEM_ADMIN', 'TENANT_USER'),
    "CREATED_AT" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    "MESSAGE" CHARACTER VARYING(500),
    "SUCCESS" BOOLEAN NOT NULL,
    "ACTOR_SYSTEM_ADMIN_ID" UUID,
    "ACTOR_USER_ID" UUID,
    "TARGET_USER_ID" UUID,
    "TENANT_ID" UUID NOT NULL
);              
ALTER TABLE "PUBLIC"."AUDIT_LOGS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8" PRIMARY KEY("ID");   
-- 9 +/- SELECT COUNT(*) FROM PUBLIC.AUDIT_LOGS;              
CREATE INDEX "PUBLIC"."IDX_AUDIT_TENANT" ON "PUBLIC"."AUDIT_LOGS"("TENANT_ID" NULLS FIRST);   
CREATE INDEX "PUBLIC"."IDX_AUDIT_ACTOR_USER" ON "PUBLIC"."AUDIT_LOGS"("ACTOR_USER_ID" NULLS FIRST);           
CREATE INDEX "PUBLIC"."IDX_AUDIT_ACTOR_SYSTEM_ADMIN" ON "PUBLIC"."AUDIT_LOGS"("ACTOR_SYSTEM_ADMIN_ID" NULLS FIRST);           
CREATE INDEX "PUBLIC"."IDX_AUDIT_TARGET_USER" ON "PUBLIC"."AUDIT_LOGS"("TARGET_USER_ID" NULLS FIRST);         
CREATE INDEX "PUBLIC"."IDX_AUDIT_ACTION" ON "PUBLIC"."AUDIT_LOGS"("ACTION" NULLS FIRST);      
CREATE INDEX "PUBLIC"."IDX_AUDIT_CREATED_AT" ON "PUBLIC"."AUDIT_LOGS"("CREATED_AT" NULLS FIRST);              
CREATE CACHED TABLE "PUBLIC"."PASSWORD_RESET_TOKENS"(
    "ID" UUID NOT NULL,
    "CREATED_AT" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    "EXPIRES_AT" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    "TOKEN_HASH" CHARACTER VARYING(255) NOT NULL,
    "USED" BOOLEAN NOT NULL,
    "USED_AT" TIMESTAMP(6) WITH TIME ZONE,
    "USER_ID" UUID NOT NULL
);  
ALTER TABLE "PUBLIC"."PASSWORD_RESET_TOKENS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_86" PRIMARY KEY("ID");       
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PASSWORD_RESET_TOKENS;   
CREATE INDEX "PUBLIC"."IDX_PASSWORD_RESET_USER" ON "PUBLIC"."PASSWORD_RESET_TOKENS"("USER_ID" NULLS FIRST);   
CREATE INDEX "PUBLIC"."IDX_PASSWORD_RESET_EXPIRES_AT" ON "PUBLIC"."PASSWORD_RESET_TOKENS"("EXPIRES_AT" NULLS FIRST);          
CREATE CACHED TABLE "PUBLIC"."REFRESH_TOKENS"(
    "ID" UUID NOT NULL,
    "CREATED_AT" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    "EXPIRES_AT" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    "REVOKED" BOOLEAN NOT NULL,
    "REVOKED_AT" TIMESTAMP(6) WITH TIME ZONE,
    "TOKEN_HASH" CHARACTER VARYING(255) NOT NULL,
    "USER_ID" UUID NOT NULL
);   
ALTER TABLE "PUBLIC"."REFRESH_TOKENS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_C" PRIMARY KEY("ID");               
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.REFRESH_TOKENS;          
CREATE INDEX "PUBLIC"."IDX_REFRESH_TOKEN_USER" ON "PUBLIC"."REFRESH_TOKENS"("USER_ID" NULLS FIRST);           
CREATE INDEX "PUBLIC"."IDX_REFRESH_TOKEN_EXPIRES_AT" ON "PUBLIC"."REFRESH_TOKENS"("EXPIRES_AT" NULLS FIRST);  
CREATE CACHED TABLE "PUBLIC"."SYSTEM_ADMINS"(
    "ID" UUID NOT NULL,
    "CREATED_AT" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    "EMAIL" CHARACTER VARYING(150) NOT NULL,
    "FAILED_LOGIN_ATTEMPTS" INTEGER NOT NULL,
    "FULL_NAME" CHARACTER VARYING(150) NOT NULL,
    "LOCKED_UNTIL" TIMESTAMP(6) WITH TIME ZONE,
    "PASSWORD_HASH" CHARACTER VARYING(255) NOT NULL,
    "STATUS" ENUM('ACTIVE', 'INACTIVE', 'SUSPENDED') NOT NULL,
    "UPDATED_AT" TIMESTAMP(6) WITH TIME ZONE
);        
ALTER TABLE "PUBLIC"."SYSTEM_ADMINS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_B" PRIMARY KEY("ID");
-- 3 +/- SELECT COUNT(*) FROM PUBLIC.SYSTEM_ADMINS;           
CREATE CACHED TABLE "PUBLIC"."TENANTS"(
    "ID" UUID NOT NULL,
    "CREATED_AT" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    "NAME" CHARACTER VARYING(150) NOT NULL,
    "SLUG" CHARACTER VARYING(100) NOT NULL,
    "STATUS" ENUM('ACTIVE', 'INACTIVE', 'SUSPENDED') NOT NULL,
    "UPDATED_AT" TIMESTAMP(6) WITH TIME ZONE
);          
ALTER TABLE "PUBLIC"."TENANTS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_D" PRIMARY KEY("ID");      
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.TENANTS; 
CREATE CACHED TABLE "PUBLIC"."PLATFORM_AUDIT_LOGS"(
    "ID" UUID NOT NULL,
    "ACTION" ENUM('SYSTEM_ADMIN_CREATED', 'SYSTEM_ADMIN_LOGIN_UNLOCKED', 'SYSTEM_ADMIN_STATUS_UPDATED') NOT NULL,
    "CREATED_AT" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    "MESSAGE" CHARACTER VARYING(500),
    "SUCCESS" BOOLEAN NOT NULL,
    "ACTOR_SYSTEM_ADMIN_ID" UUID,
    "TARGET_SYSTEM_ADMIN_ID" UUID
);     
ALTER TABLE "PUBLIC"."PLATFORM_AUDIT_LOGS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_DF" PRIMARY KEY("ID");         
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.PLATFORM_AUDIT_LOGS;     
CREATE INDEX "PUBLIC"."IDX_PLATFORM_AUDIT_ACTOR" ON "PUBLIC"."PLATFORM_AUDIT_LOGS"("ACTOR_SYSTEM_ADMIN_ID" NULLS FIRST);      
CREATE INDEX "PUBLIC"."IDX_PLATFORM_AUDIT_TARGET" ON "PUBLIC"."PLATFORM_AUDIT_LOGS"("TARGET_SYSTEM_ADMIN_ID" NULLS FIRST);    
CREATE INDEX "PUBLIC"."IDX_PLATFORM_AUDIT_ACTION" ON "PUBLIC"."PLATFORM_AUDIT_LOGS"("ACTION" NULLS FIRST);    
CREATE INDEX "PUBLIC"."IDX_PLATFORM_AUDIT_CREATED_AT" ON "PUBLIC"."PLATFORM_AUDIT_LOGS"("CREATED_AT" NULLS FIRST);            
ALTER TABLE "PUBLIC"."REFRESH_TOKENS" ADD CONSTRAINT "PUBLIC"."UK_REFRESH_TOKEN_HASH" UNIQUE NULLS DISTINCT ("TOKEN_HASH");   
ALTER TABLE "PUBLIC"."PASSWORD_RESET_TOKENS" ADD CONSTRAINT "PUBLIC"."UK_PASSWORD_RESET_TOKEN_HASH" UNIQUE NULLS DISTINCT ("TOKEN_HASH");     
ALTER TABLE "PUBLIC"."APP_USERS" ADD CONSTRAINT "PUBLIC"."UK_USER_EMAIL_PER_TENANT" UNIQUE NULLS DISTINCT ("TENANT_ID", "EMAIL");             
ALTER TABLE "PUBLIC"."TENANTS" ADD CONSTRAINT "PUBLIC"."UK_TENANT_SLUG" UNIQUE NULLS DISTINCT ("SLUG");       
ALTER TABLE "PUBLIC"."SYSTEM_ADMINS" ADD CONSTRAINT "PUBLIC"."UK_SYSTEM_ADMIN_EMAIL" UNIQUE NULLS DISTINCT ("EMAIL");         
ALTER TABLE "PUBLIC"."APP_USERS" ADD CONSTRAINT "PUBLIC"."FK63I36DPF43OGC0MIJOYHCH94A" FOREIGN KEY("TENANT_ID") REFERENCES "PUBLIC"."TENANTS"("ID") NOCHECK;  
ALTER TABLE "PUBLIC"."AUDIT_LOGS" ADD CONSTRAINT "PUBLIC"."FK7LLJXU5T4WN1GVKKG69748OGQ" FOREIGN KEY("TARGET_USER_ID") REFERENCES "PUBLIC"."APP_USERS"("ID") NOCHECK;          
ALTER TABLE "PUBLIC"."PLATFORM_AUDIT_LOGS" ADD CONSTRAINT "PUBLIC"."FK6D0NP5W6TIRI0EYIBMPHE7TDU" FOREIGN KEY("ACTOR_SYSTEM_ADMIN_ID") REFERENCES "PUBLIC"."SYSTEM_ADMINS"("ID") NOCHECK;      
ALTER TABLE "PUBLIC"."PLATFORM_AUDIT_LOGS" ADD CONSTRAINT "PUBLIC"."FKGD5RXBFN960WATA355TFSV80C" FOREIGN KEY("TARGET_SYSTEM_ADMIN_ID") REFERENCES "PUBLIC"."SYSTEM_ADMINS"("ID") NOCHECK;     
ALTER TABLE "PUBLIC"."PASSWORD_RESET_TOKENS" ADD CONSTRAINT "PUBLIC"."FKK4VAGUHRXS5JL3LQTSHGLAXO8" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."APP_USERS"("ID") NOCHECK;      
ALTER TABLE "PUBLIC"."AUDIT_LOGS" ADD CONSTRAINT "PUBLIC"."FKT6GX0SM49USDF4PAHVON2PXHP" FOREIGN KEY("ACTOR_USER_ID") REFERENCES "PUBLIC"."APP_USERS"("ID") NOCHECK;           
ALTER TABLE "PUBLIC"."AUDIT_LOGS" ADD CONSTRAINT "PUBLIC"."FKQQUET9030XTKK7JYVQWUY1BYU" FOREIGN KEY("TENANT_ID") REFERENCES "PUBLIC"."TENANTS"("ID") NOCHECK; 
ALTER TABLE "PUBLIC"."AUDIT_LOGS" ADD CONSTRAINT "PUBLIC"."FKO83QXA340IQ3193OPD05I18I2" FOREIGN KEY("ACTOR_SYSTEM_ADMIN_ID") REFERENCES "PUBLIC"."SYSTEM_ADMINS"("ID") NOCHECK;               
ALTER TABLE "PUBLIC"."REFRESH_TOKENS" ADD CONSTRAINT "PUBLIC"."FKT72GIJOAK5YUFXWS745GWFLIS" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."APP_USERS"("ID") NOCHECK;             
