package com.chacha.multitenantsaas.entity;

public enum AuditAction {
    TENANT_ONBOARDED,
    TENANT_UPDATED,
    TENANT_STATUS_UPDATED,
    TENANT_DEACTIVATED,
    USER_CREATED,
    USER_UPDATED,
    USER_ROLE_UPDATED,
    USER_STATUS_UPDATED,
    USER_DEACTIVATED,
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    LOGOUT,
    LOGOUT_ALL,
    TOKEN_REFRESH,
    PASSWORD_CHANGED,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET_COMPLETED
}