package com.chacha.multitenantsaas.entity;

public enum AuditAction {

    TENANT_ONBOARDED,
    TENANT_UPDATED,
    TENANT_STATUS_UPDATED,
    TENANT_DEACTIVATED,

    USER_CREATED,
    USER_UPDATED,
    USER_ROLE_UPDATED,
    USER_STATUS_UPDATED,
    USER_DEACTIVATED,
    USER_LOGIN_UNLOCKED,

    LOGIN_SUCCESS,
    LOGIN_FAILED,
    LOGOUT,
    LOGOUT_ALL,
    TOKEN_REFRESH,
    PASSWORD_CHANGED,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET_COMPLETED,

    ORG_UNIT_CREATED,
    ORG_UNIT_UPDATED,
    ORG_UNIT_STATUS_UPDATED,
    ORG_UNIT_MOVED,

    ORG_ASSIGNMENT_CREATED,
    ORG_ASSIGNMENT_DEACTIVATED,

    AUTH_PERMISSION_CREATED,
    AUTH_PERMISSION_DEACTIVATED,

    AUTH_ROLES_INITIALIZED,
    AUTH_ROLE_CREATED,
    AUTH_ROLE_PERMISSIONS_UPDATED,
    AUTH_ROLE_DEACTIVATED,

    AUTH_USER_ROLE_ASSIGNED,
    AUTH_USER_ROLE_ASSIGNMENT_DEACTIVATED,

    PROJECT_CREATED,
    PROJECT_UPDATED,
    PROJECT_STATUS_UPDATED,
    PROJECT_ARCHIVED,

    PROJECT_MEMBER_ADDED,
    PROJECT_MEMBER_ROLE_UPDATED,
    PROJECT_MEMBER_REMOVED,

    TASK_CREATED,
    TASK_UPDATED,
    TASK_STATUS_UPDATED,
    TASK_ASSIGNEE_UPDATED,
    TASK_CANCELLED
}