package com.chacha.multitenantsaas.entity;

public enum AuditAction {
    TENANT_ONBOARDED,
    TENANT_UPDATED,
    TENANT_STATUS_UPDATED,
    TENANT_DEACTIVATED,

    USER_CREATED,
    USER_UPDATED,
    USER_ROLE_UPDATED,
    USER_STATUS_UPDATED,
    USER_DEACTIVATED,
    USER_LOGIN_UNLOCKED,

    LOGIN_SUCCESS,
    LOGIN_FAILED,
    LOGOUT,
    LOGOUT_ALL,
    TOKEN_REFRESH,
    PASSWORD_CHANGED,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET_COMPLETED,

    ORG_UNIT_CREATED,
    ORG_UNIT_UPDATED,
    ORG_UNIT_STATUS_UPDATED,
    ORG_UNIT_MOVED,

    ORG_ASSIGNMENT_CREATED,
    ORG_ASSIGNMENT_DEACTIVATED,

    AUTH_PERMISSION_CREATED,
    AUTH_PERMISSION_DEACTIVATED,

    AUTH_ROLES_INITIALIZED,
    AUTH_ROLE_CREATED,
    AUTH_ROLE_PERMISSIONS_UPDATED,
    AUTH_ROLE_DEACTIVATED,

    AUTH_USER_ROLE_ASSIGNED,
    AUTH_USER_ROLE_ASSIGNMENT_DEACTIVATED,
    AUTH_ACCESS_EXPLAINED,

    PROJECT_CREATED,
    PROJECT_UPDATED,
    PROJECT_STATUS_UPDATED,
    PROJECT_ARCHIVED,

    PROJECT_MEMBER_ADDED,
    PROJECT_MEMBER_ROLE_UPDATED,
    PROJECT_MEMBER_REMOVED,

    TASK_CREATED,
    TASK_UPDATED,
    TASK_STATUS_UPDATED,
    TASK_ASSIGNEE_UPDATED,
    TASK_CANCELLED,
    TASK_COMMENT_CREATED,
    TASK_COMMENT_REPLIED,
    TASK_COMMENT_UPDATED,
    TASK_COMMENT_DELETED,
    TASK_COMMENT_PINNED,
    TASK_COMMENT_UNPINNED,
    TASK_ATTACHMENT_CREATED,
    TASK_ATTACHMENT_DELETED,

    API_KEY_CREATED,
    API_KEY_REVOKED,

    OUTBOUND_WEBHOOK_CREATED,
    OUTBOUND_WEBHOOK_UPDATED,
    OUTBOUND_WEBHOOK_SECRET_ROTATED,
    OUTBOUND_WEBHOOK_ARCHIVED,
    OUTBOUND_WEBHOOK_DELIVERY_REPLAYED,

    IDENTITY_PROVIDER_CONFIGURED,
    IDENTITY_PROVIDER_UPDATED,
    IDENTITY_PROVIDER_CLIENT_SECRET_ROTATED,
    IDENTITY_PROVIDER_VERIFIED,
    IDENTITY_PROVIDER_IDENTITY_LINKED,
    IDENTITY_PROVIDER_SSO_POLICY_UPDATED,
    IDENTITY_PROVIDER_LOGIN_SUCCESS,
    IDENTITY_PROVIDER_LOGIN_FAILED,
    IDENTITY_PROVIDER_BREAK_GLASS_LOGIN,
    IDENTITY_PROVIDER_ENABLED,
    IDENTITY_PROVIDER_DISABLED,

    TENANT_SUBSCRIPTION_STARTED,
    TENANT_SUBSCRIPTION_PLAN_CHANGED,
    TENANT_SUBSCRIPTION_LIFECYCLE_UPDATED
}
