package com.chacha.multitenantsaas.entity;

public enum PlatformAuditAction {
    SYSTEM_ADMIN_CREATED,
    SYSTEM_ADMIN_STATUS_UPDATED,
    SYSTEM_ADMIN_LOGIN_UNLOCKED,

    SUBSCRIPTION_PLAN_CREATED,
    SUBSCRIPTION_PLAN_UPDATED,
    SUBSCRIPTION_PLAN_STATUS_UPDATED,

    TENANT_SUBSCRIPTION_STARTED,
    TENANT_SUBSCRIPTION_PLAN_CHANGED,
    TENANT_SUBSCRIPTION_LIFECYCLE_UPDATED
}
