package com.chacha.multitenantsaas.common;

public enum ErrorCode {
    VALIDATION_FAILED,

    INVALID_REQUEST,
    INVALID_PARAMETER,
    MALFORMED_REQUEST,

    RESOURCE_NOT_FOUND,
    RESOURCE_ALREADY_EXISTS,

    AUTHENTICATION_REQUIRED,
    AUTHENTICATION_FAILED,
    ACCESS_DENIED,
    RATE_LIMITED,

    TEMPORARY_DATABASE_CONFLICT,
    BILLING_PROVIDER_ERROR,

    INTERNAL_SERVER_ERROR
}
